### PR TITLE
Personal Schedules Place Holders

### PR DESCRIPTION
**Pull request by tiny-babies**
# Overview

Add Page Place Holders for Personal Schedules and tests

# Details

image
image
image
image
image

### CODE REVIEW

**Review by AlexLaiUCSB — APPROVED** [review]
LGTM

**Review by pconrad — DISMISSED** [review]
LGTM!  10 points

**Comment by pconrad** [comment]
Just waiting on CI/CD to pass before merging...  I'll check back in 20 minutes or so (front end mutation testing takes about 20 minutes)

**Review by AlexLaiUCSB — APPROVED** [review]
Pulled to local. LGTM!

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
