### PR TITLE
Made UCSB Subjects get endpoint unprotected

### LINKED ISSUE #70: Backend endpoint to list subjects should be publically available (not protected for logged in users only)
Otherwise ,you can't populate the drop down menu for subject areas

### PR DESCRIPTION
**Pull request by sidd328**
# Overview

UCSB Subjects get endpoint now works for any person accessing the page (logged in or not)

# Issues Addressed

Closes #70

### CODE REVIEW

**Review by LucienLuc — DISMISSED** [review]
LGTM!

**Review by asharma381 — APPROVED** [review]
Looks good to me. Loads of changes, I challenge you to make this into a smaller PR next time.🥇  👀  - Just kidding

**Comment by sidd328** [comment]
> Looks good to me. Loads of changes, 🥇 if you can try making this into a smaller PR next time. 👀 - Just kidding

Yes, I thought about putting each line change in a new PR but I had to stay true to our w22-5pm-1 roots and put everything into 1 PR

**Review by LucienLuc — APPROVED** [review]
LGTM!

**Pull request closed without merging**
