### PR TITLE
sg-changed quarter to QYY on PerSchedTable

### PR DESCRIPTION
**Pull request by ScottUCSB**
This is just a draft for now, working on changing the display of quarter on the personal schedule table. There's a function that should convert it in the util. Just need to figure out how to properly employ it.

### CODE REVIEW

**Comment by ScottUCSB** [comment]
image
Just need to fix the tests

**Comment by ScottUCSB** [comment]
In addition to the hints given by Professor Conrad, add an id 'quarter' in the table right underneath the util function (thank you Alex)

**Review by AlexLaiUCSB — APPROVED** [review]
LGTM

**Review by pconrad — APPROVED** [review]
LGTM!

https://ucsb-cs156-w22.github.io/team04-w22-5pm-courses-docs-qa/storybook-qa/w22-5pm-2-sg-QYY-format-instead-of-YYYYQ/?path=/story/components-personalschedules-personalschedulestable--three-subjects&args=personalSchedules[0].quarter:20223

**Comment by pconrad** [comment]
I think this is mergeable for 10 points once CI/CD finishes....

**Review by pconrad — COMMENTED** [review]
LGTM

**Pull request merged**
